global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'railway-prom'
  depends_on:
    - pg-exporter
    - redis-exporter

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090'] # Use the service name

  - job_name: 'postgres'
    scrape_interval: 5s
    static_configs:
      - targets: ['pg-exporter:9187'] # Use the service name

  - job_name: 'redis'
    scrape_interval: 5s
    static_configs:
      - targets: ['redis-exporter:9121'] # Use the service name
